### ISSUE TITLE
CMD + plus not increasing font size

### ISSUE THREAD

**Issue by stefanjudis** [teesloane/moonview#28]
Hey hey,

lovin' the idea of this app.
To really use it, increase/decrease of font size would be really nice.

Thanks for the work. :)

**Comment by teesloane** [comment]
Hi there stefan! Thanks for the feedback and kind words.

You can actually increase font size by opening up the preferences by pressing `cmd + ,` or `ctrl + ,` on windows. 

![screenshot 2016-09-20 08 25 20](https://cloud.githubusercontent.com/assets/12987958/18670057/efbf5952-7f0b-11e6-94e0-d5aef0362fd2.png)

**Comment by stefanjudis** [comment]
Aah nice... Cool 👍 

That's what I tried, but it didn't work with `cmd` or `ctrl` and `+`.
I assume my German keyboard is the reason. :)

I'm on a  mac. :) and use version `0.0.1 (0.0.1)`.

**Comment by teesloane** [comment]
Hmm. Good point. I hadn't thought to make `ctrl +/-` as a means of increasing font size. I will find some time to implement that in the future perhaps. @jondcoleman Would you be interested in setting that up?

**Comment by jondcoleman** [comment]
I think typically `ctrl +/-` is for zoom, not for changing font size so I would hesitate to implement that.  Maybe another shortcut?

**Comment by jondcoleman** [comment]
Well, I spoke too soon.  Sublime uses that for font size.

Atom uses `Ctrl`+`Shift`+`=/-`.

**Comment by teesloane** [comment]
Yeah, could be worth implementing.
