### ISSUE TITLE
Make editor width absolute

### ISSUE THREAD

**Issue by stefanjudis** [teesloane/moonview#29]
Hey hey,

I guess the editor size is set up in relative units right now. 
It would be cool when It would be set as an absolute value, because when dealing with relative units, i have to adjust the width constantly when changing the window size. :)

![fixed-size](https://cloud.githubusercontent.com/assets/962099/18670549/c01e21a8-7f40-11e6-8b37-40f804cbaa68.gif)

Thanks. :)

**Comment by teesloane** [comment]
Hmm. good point. I can see how that would be frustrating. This shouldn't be a difficult change, thanks for bringing it up (the gif really helped too.) I will try and find a solution for this soon.

**Comment by teesloane** [comment]
All pushed in the newest release (0.1.1)

**Comment by stefanjudis** [comment]
Sweet!. Thanks. :)
